# Generated by Django 5.2.5 on 2025-08-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('company_logo', models.URLField(default='https://remoteok.com/assets/logo.png', max_length=500)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=500)),
                ('tags', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=9)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=9)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
